import Head from 'next/head'
import Image from 'next/image'
import { Payment, HomeStyle } from '../styles/Home'

export default function Home () {
  return (
    <HomeStyle>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Payment>
        <div id="produto">
          <Image
            alt='moeda-image'
            src='/moeda.jpg'
            layout='intrinsic'
            width={400}
            height={350}
          />
        </div>

      </Payment>
    </HomeStyle>
  )
}
